<table cellpadding="1" cellspacing="1" border="0" width="95%" align="center">
<tbody>
	<tr>
	  <td>
		<table cellpadding="2" cellspacing="2" border="0" width="100%" align="center">
		<tbody>
		  <tr>
			<td width="100%" align="center" valign="top">
			  <big><b><font size="6" face="Arial, Helvetica, sans-serif" color="#000000">
			  Uppsala,SE Weather</font></b></big>
			</td>
		  </tr>
		  <tr>
			<td width="100%" align="center" valign="top">
			  <font size="2" face="Arial, Helvetica, sans-serif" color="#000000">
			  <b>59.9 N - 17.7 E - 
			  24 m</b></font>
			</td>
		  </tr>
		  <tr>
			<td valign="top" align="center">
			  <font size="4" face="Arial, Helvetica, sans-serif" color="#000000">
			  08/09/21 19:37:10
			  </font>
			</td>
		  </tr>
          <tr>
            <td width="100%" align="center" valign="top">
              <font size="2" face="Arial, Helvetica, sans-serif" color="#000000">
              Sunrise:04:51 - Sunset:20:59 - Moon:Waxing 2% Full
              </font>
            </td>
          </tr>
		</tbody>
		</table>
	  </td>
	</tr>
</tbody>
</table>

