<table cellspacing="1" cellpadding="0" width="100%" align="left" border="0">
<tbody>
  <tr>
    <td align="center">
      <table cellspacing="1" cellpadding="0" width="100%" align="left" border="1">
      <tbody>
        <tr height="20">
          <td width="50%">
            <font face="Tw Cen MT" color="#000000">
            <strong>Temperature:</strong>
            </font>
          </td>
          <td width="50%" align="left">
            <font face="Tw Cen MT" color="#000000">
            <b>18.9 C</b>
            </font>
          </td>
        </tr>
        <tr height="20">
          <td width="50%">
            <font face="Tw Cen MT" color="#000000">
            <strong>Wind Chill:</strong>
            </font>
          </td>
          <td width="50%" align="left">
            <font face="Tw Cen MT" color="#000000">
            <b>18.9 C</b>
            </font>
          </td>
        </tr>
        <tr height="20">
          <td width="50%">
            <font face="Tw Cen MT" color="#000000">
            <strong>Heat Index:</strong>
            </font>
          </td>
          <td width="50%" align="left">
            <font face="Tw Cen MT" color="#000000">
            <b>18.9 C</b>
            </font>
          </td>
        </tr>
        <tr height="20">
          <td width="50%">
            <font face="Tw Cen MT" color="#000000">
            <strong>Apparent Temp:</strong>
            </font>
          </td>
          <td width="50%" align="left">
            <font face="Tw Cen MT" color="#000000">
            <b>-15.7 C</b>
            </font>
          </td>
        </tr>
        <tr height="20">
          <td width="50%">
            <font face="Tw Cen MT" color="#000000">
            <strong>Wet Bulb Temp:</strong>
            </font>
          </td>
          <td width="50%" align="left">
            <font face="Tw Cen MT" color="#000000">
            <b>15.7 C</b>
            </font>
          </td>
        </tr>
        <tr height="20">
          <td width="50%">
            <font face="Tw Cen MT" color="#000000">
            <strong>Dewpoint:</strong>
            </font>
          </td>
          <td width="50%" align="left">
            <font face="Tw Cen MT" color="#000000">
            <b>13.5 C</b>
            </font>
          </td>
        </tr>
        <tr height="20">
          <td width="50%">
            <font face="Tw Cen MT" color="#000000">
            <strong>Humidity:</strong>
            </font>
          </td>
          <td width="50%" align="left">
            <font face="Tw Cen MT" color="#000000">
            <b>71 %</b>
            </font>
          </td>
        </tr>
        <tr height="20">
          <td width="50%">
            <font face="Tw Cen MT" color="#000000">
            <strong>Barometer:</strong>
            </font>
          </td>
          <td width="50%" align="left">
            <font face="Tw Cen MT" color="#000000">
            <b>1008.6&nbsp; mb&nbsp;+</b>
            </font>
          </td>
        </tr>
        <tr height="20">
          <td width="50%">
            <font face="Tw Cen MT" color="#000000">
            <strong>Wind:</strong>
            </font>
          </td>
          <td width="50%" align="left">
            <font face="Tw Cen MT" color="#000000">
            <b>NW&nbsp;&nbsp;at&nbsp;&nbsp;
            51.0&nbsp; m/s</b>
            </font>
          </td>
        </tr>
        <tr height="20">
          <td width="50%">
            <font face="Tw Cen MT" color="#000000">
            <strong>High Wind:</strong>
            </font>
          </td>
          <td width="50%" align="left">
            <font face="Tw Cen MT" color="#000000">
            <b>51.0  m/s at 
            00:00</b>
            </font>
          </td>
        </tr>
        <tr height="20">
          <td width="50%">
            <font face="Tw Cen MT" color="#000000">
            <strong>Recent Avg Wind:</strong>
            </font>
          </td>
          <td width="50%" align="left">
            <font face="Tw Cen MT" color="#000000">
            <b>51.0  m/s</b>
            </font>
          </td>
        </tr>
        <tr height="20">
          <td width="50%">
            <font face="Tw Cen MT" color="#000000">
            <strong>Recent Beaufort Scale:</strong>
            </font>
          </td>
          <td width="50%" align="left">
            <font face="Tw Cen MT" color="#000000">
            <b>Hurricane</b>
            </font>
          </td>
        </tr>
        <tr height="20">
          <td width="50%">
            <font face="Tw Cen MT" color="#000000">
            <strong>Today's Rain:</strong>
            </font>
          </td>
          <td width="50%" align="left">
            <font face="Tw Cen MT" color="#000000">
            <b>0.00&nbsp; mm</b>
            </font>
          </td>
        </tr>
        <tr height="20">
          <td width="50%">
            <font face="Tw Cen MT" color="#000000">
            <strong>Rain Rate:</strong>
            </font>
          </td>
          <td width="50%" align="left">
            <font face="Tw Cen MT" color="#000000">
            <b>0.00&nbsp; mm/h</b>
            </font>
          </td>
        </tr>
        <tr height="20">
          <td width="50%">
            <font face="Tw Cen MT" color="#000000">
            <strong>High Rain Rate:</strong>
            </font>
          </td>
          <td width="50%" align="left">
            <font face="Tw Cen MT" color="#000000">
            <b>0.00  mm/h at 
            -----</b>
            </font>
          </td>
        </tr>
        <tr height="20">
          <td width="50%">
            <font face="Tw Cen MT" color="#000000">
            <strong>Storm Total:</strong>
            </font>
          </td>
          <td width="50%" align="left">
            <font face="Tw Cen MT" color="#000000">
            <b>0.00&nbsp; mm</b>
            </font>
          </td>
        </tr>
        <tr height="20">
          <td width="50%">
            <font face="Tw Cen MT" color="#000000">
            <strong>Monthly Rain:</strong>
            </font>
          </td>
          <td width="50%" align="left">
            <font face="Tw Cen MT" color="#000000">
            <b>22.28&nbsp; mm</b>
            </font>
          </td>
        </tr>
        <tr height="20">
          <td width="50%">
            <font face="Tw Cen MT" color="#000000">
            <strong>Yearly Rain (JAN):</strong>
            </font>
          </td>
          <td width="50%" align="left">
            <font face="Tw Cen MT" color="#000000">
            <b>162.14&nbsp; mm</b>
            </font>
          </td>
        </tr>
        <tr height="20">
          <td width="50%">
            <font face="Tw Cen MT" color="#000000">
            <strong>Air Density:</strong>
            </font>
          </td>
          <td width="50%" align="left">
            <font face="Tw Cen MT" color="#000000">
            <b>1.196&nbsp; kg/m^3</b>
            </font>
          </td>
        </tr>
        <tr height="20">
          <td width="50%">
            <font face="Tw Cen MT" color="#000000">
            <strong>Est. Cumulus Base:</strong>
            </font>
          </td>
          <td width="50%" align="left">
            <font face="Tw Cen MT" color="#000000">
            <b>673&nbsp; m</b>
            </font>
          </td>
        </tr>
        <tr height="20">
          <td width="50%">
            <font face="Tw Cen MT" color="#000000">
            <strong>High Temperature:</strong>
            </font>
          </td>
          <td width="50%" align="left">
            <font face="Tw Cen MT" color="#000000">
            <b>22.4 C at 
            14:27</b>
            </font>
          </td>
        </tr>
        <tr height="20">
          <td width="50%">
            <font face="Tw Cen MT" color="#000000">
            <strong>Low Temperature:</strong>
            </font>
          </td>
          <td width="50%" align="left">
            <font face="Tw Cen MT" color="#000000">
            <b>12.8 C at 
            04:55</b>
            </font>
          </td>
        </tr>
        <tr height="20">
          <td width="50%">
            <font face="Tw Cen MT" color="#000000">
            <strong>High Heat Index:</strong>
            </font>
          </td>
          <td width="50%" align="left">
            <font face="Tw Cen MT" color="#000000">
            <b>22.4 C at 
            14:27</b>
            </font>
          </td>
        </tr>
        <tr height="20">
          <td width="50%">
            <font face="Tw Cen MT" color="#000000">
            <strong>Low Wind Chill:</strong>
            </font>
          </td>
          <td width="50%" align="left">
            <font face="Tw Cen MT" color="#000000">
            <b>12.8 C at 
            04:55</b>
            </font>
          </td>
        </tr>
        <tr height="20">
          <td width="50%">
            <font face="Tw Cen MT" color="#000000">
            <strong>High Humidity:</strong>
            </font>
          </td>
          <td width="50%" align="left">
            <font face="Tw Cen MT" color="#000000">
            <b>84 % at 
            01:54</b>
            </font>
          </td>
        </tr>
        <tr height="20">
          <td width="50%">
            <font face="Tw Cen MT" color="#000000">
            <strong>Low Humidity:</strong>
            </font>
          </td>
          <td width="50%" align="left">
            <font face="Tw Cen MT" color="#000000">
            <b>64 % at 
            14:30</b>
            </font>
          </td>
        </tr>
        <tr height="20">
          <td width="50%">
            <font face="Tw Cen MT" color="#000000">
            <strong>High Dewpoint:</strong>
            </font>
          </td>
          <td width="50%" align="left">
            <font face="Tw Cen MT" color="#000000">
            <b>16.4 C at 
            11:52</b>
            </font>
          </td>
        </tr>
        <tr height="20">
          <td width="50%">
            <font face="Tw Cen MT" color="#000000">
            <strong>Low Dewpoint:</strong>
            </font>
          </td>
          <td width="50%" align="left">
            <font face="Tw Cen MT" color="#000000">
            <b>10.2 C at 
            04:55</b>
            </font>
          </td>
        </tr>
        <tr height="20">
          <td width="50%">
            <font face="Tw Cen MT" color="#000000">
            <strong>High Barometer:</strong>
            </font>
          </td>
          <td width="50%" align="left">
            <font face="Tw Cen MT" color="#000000">
            <b>1008.8  mb at 
            18:52</b>
            </font>
          </td>
        </tr>
        <tr height="20">
          <td width="50%">
            <font face="Tw Cen MT" color="#000000">
            <strong>Low Barometer:</strong>
            </font>
          </td>
          <td width="50%" align="left">
            <font face="Tw Cen MT" color="#000000">
            <b>1004.6  mb at 
            00:06</b>
            </font>
          </td>
        </tr>
      </tbody>
      </table>
    </td>
  </tr>
</tbody>
</table>

